"""
Simple library for calling applescripts generated by python code

http://www.leancrew.com/all-this/2013/03/combining-python-and-applescript/
"""
import subprocess
import os

graffle_export_script = """
# Taken from here:
# https://martinfowler.com/articles/2017-graffle-export.html
# TODO: select the right canvas
on convertGraffleFile(graffleFile, outputFile)
   tell application "OmniGraffle"
        set area type of current export settings to all graphics
        open graffleFile
        tell front document to save in file outputFile
        close front document
    end tell
end convertGraffleFile

convertGraffleFile("%s", "%s")
"""
  
def asrun(ascript):
    "Run the given AppleScript and return the standard output and error."
  
    osa = subprocess.Popen(['osascript', '-'],
                           stdin=subprocess.PIPE,
                           stdout=subprocess.PIPE)
    return osa.communicate(ascript)[0]
  
def asquote(astr):
    "Return the AppleScript equivalent of the given string."
    
    astr = astr.replace('"', '" & quote & "')
    return '"{}"'.format(astr)

def export_graffle(graffle_file, outfile, canvasname):
    # TODO: canvasname
    ascript = graffle_export_script % (macpath(graffle_file), macpath(outfile))
    print ascript
    asrun(ascript)

def macpath(fname):
    return os.path.abspath(fname).replace("/", ":").lstrip(":")

